### PR TITLE
PR of #67

### PR DESCRIPTION
**Pull request by realivanjx**
Here is a solution of my problem (#67). I also added a stream-like function signature to help those who need to access usb like i did in windows.

### CODE REVIEW

**Comment by MelbourneDeveloper** [comment]
@realivanjx I will work through this in the next couple of days,

**Comment by MelbourneDeveloper** [comment]
@realivanjx I can see where you're going with this. 

I'm thinking something like [this](https://github.com/MelbourneDeveloper/Device.Net/blob/realdevelop/src/Device.Net/DataSplitter.cs). Yes? No? The code should be shared across all devices - not just WinUsbDevice.

But, if you're going to go to the trouble of writing the code to split up a large array in to smaller chunks, why not include the code that iterates through the large array of data?

**Comment by realivanjx** [comment]
Thats good if you can integrate that pattern with the entire implementation of this library. Im just too focused on `Usb.Net` project. 

In my case i dont need to split any data to smaller chunks (64 bytes previously), because like i said, either `winusb` already handle this (which is should be much much faster than C#) or the device is already capable to handle it. Again, my case is for motorola (or any devices that implements fastboot) so the latter case is possible too.

**Comment by MelbourneDeveloper** [comment]
@realivanjx my code is exactly the same as your code. It doesn't need to be added to WinUsbDevice. the only difference is that I'm using dependency injection so that any device can use your code instead of it being stuck in WinUsbDevice.

**Comment by MelbourneDeveloper** [comment]
Can you see how this solves your issue?

**Comment by realivanjx** [comment]
My code alone already solves my issue though, but your solution is better because you put it on `Device.Net`.

Also the name `DataSplitter` is not right because it doesnt split any data :) . Maybe just put those 2 functions with the original read and write function.

**Comment by realivanjx** [comment]
I tried to put those under `Device.Net` too yesterday but then i realize that `IDevice` is an interface and i cant add custom methods to it without implementing my methods manually to the other platforms. I still prefer putting those alongside your original read and write methods (method overloading).

**Comment by MelbourneDeveloper** [comment]
@realivanjx the interfaces are deliberately very simple. The concept is about dependency injection. Helper classes can be built to inject the dependency in so the logic can be used with any dependency. There's no point baking the logic in to one concrete class, when all classes can use the logic.

Anyway, I've added the ability to specify the buffer sizes here: https://github.com/MelbourneDeveloper/Device.Net/blob/dee398c6ef03cd4283c50eaa7a6b7d64fa16cbaa/src/Usb.Net/Windows/WindowsUsbDevice.cs#L35

I've just done a NuGet release so you can specify the sizes:
https://www.nuget.org/packages/Usb.Net/2.9.0

**Comment by MelbourneDeveloper** [comment]
@realivanjx does the above solve your problem?

**Comment by realivanjx** [comment]
Yea im aware of DI and interfaces you used there. I just dont know that you can/allow add helper class like that. Thats good then no need to add on each implementations. And yes that should solve my problem but i can just test for windows one. I dont know about the other.

Also please change the name of the class. It is just not right :)

Ivan Kara

________________________________

**Comment by MelbourneDeveloper** [comment]
> I just dont know that you can/allow add helper class like that.

Why not?

> Also please change the name of the class.

Do I really need to add the class? Do you think it's something that Device.Net should have? 

> that should solve my problem but i can just test for windows one. I dont know about the other.

Let me know if you have a problem with another platform. I will fix it.

**Comment by realivanjx** [comment]
Yes. IMO you should have those 2 functions i proposed. I never said that you should add them into a separate helper class but if you can add those 2 functions into IDevice and implement those into all platforms that is much more preferable.

**Comment by MelbourneDeveloper** [comment]
@realivanjx 

> IMO you should have those 2 functions i proposed. I never said that you should add them into a separate helper class but if you can add those 2 functions into IDevice

Nope. That's not necessary. I can put them in a helper class so they can be used the same way. But, I'm not going to add those methods because they just call the existing methods. It's a design choice. If that stops you from working please let me know why. I'd need a code example or something to explain why those extra overloads are necessary.

> implement those into all platforms

If you have problems with buffer size on other platforms, please let me know.

**Comment by realivanjx** [comment]
No that wont stop me from using this awesome library :)

If you want to add those add into separate class then go for it. I am more than happy to have those functions than not at all.

**Comment by realivanjx** [comment]
Are you going to change the class name though?

**Comment by MelbourneDeveloper** [comment]
@realivanjx great!

I understand why it might be handy to have those overloads, but please understand, I have spent hours and hours and hours trying to keep the interfaces as simple as possible. That means that as many helpers as necessary can be made without bloating the public interface.

What do you want to call the class?

**Comment by realivanjx** [comment]
How about `IoHelper` or `IOHelper` ? I am also confused about the class name you should use in this case...

**Comment by MelbourneDeveloper** [comment]
Something like that sounds about right. I will have a think about it...

**Comment by MelbourneDeveloper** [comment]
@realivanjx are you able to post all the code including the part where you iterate through the 100 meg of data?

**Comment by realivanjx** [comment]
i am about to create a new repo about fastboot flashing on my gitlab account and share it with you but it is still using dll of your library instead of the nuget package until you released those changes

**Comment by realivanjx** [comment]
Here you go: https://gitlab.com/ivanjx/fastboot-flashing

**Comment by realivanjx** [comment]
usually each phone can accept from 200-500 MB

**Comment by MelbourneDeveloper** [comment]
@realivanjx that's awesome!

So, you've tested Device.net with this and it works?

I'd really like to put a link to this as a sample so that other people can see what you've done there.

**Comment by realivanjx** [comment]
i think the whole device.net will work. right now for fastboot im just using the windows usb.net one and it works very good

**Comment by realivanjx** [comment]
but i think for windows it is better to use winusb than libusb. i tried using libusb (with LibUsbDotNet) and it doesnt work very well (some devices work 100%, some can only read phone info, some cant even connect at all).

**Comment by MelbourneDeveloper** [comment]
@realivanjx thanks for this code. It's now in the develop branch as BulkIOService

**Pull request closed without merging**
