### PR TITLE
Adds attempt at adding USB control transfers.

### PR DESCRIPTION
**Pull request by networkfusion**
Work towards https://github.com/MelbourneDeveloper/Device.Net/issues/126

TODO:

* Expose USB setup packets
* Make commands Async?
* Correct WinUsb interface handle

and probably more...

### CODE REVIEW

**Comment by MelbourneDeveloper** [comment]
@networkfusion Hi. I get the general gist of what is going on here. Firstly, I'll need a device to test with, but also, these changes need to fit with the rest of the framework - i.e. the public interface. This is lib usb specific. 

Which platforms are you targeting?

**Comment by networkfusion** [comment]
Windows .net core 3.1 and potentially linux in the future. `WinUsbApiCalls.WinUsb_ControlTransfer` seems to make it possible for windows. I will keep going with what I have as time allows to see where I can get to. Hopefully a board will be winging its way to you very soon.

**Comment by MelbourneDeveloper** [comment]
@networkfusion cool. Maybe hit pause until I get the device. I'll just likely try to get it working on the windows version first - not lib USB.

**Comment by MelbourneDeveloper** [comment]
@networkfusion Hi. I think I was wrong. I see that you've made these changes across a couple of implementations. Sorry, I was in a rush the other day.

Looking forward to testing this out.

Again, I'll need some kind of integration test to work with.

**Pull request closed without merging**
