### PR TITLE
Add SourceLink support for all csproj files

### PR DESCRIPTION
**Pull request by LiorBanai**
adding [SourceLink](https://github.com/dotnet/sourcelink) to enable debugging inside visual studio the source code.
also fixing missing sample project in the example solution for windows

### CODE REVIEW

**Comment by MelbourneDeveloper** [comment]
@LiorBanai Hi. I'm so sorry I didn't see this! Thankyou for submitting. I will review ASAP.,

**Comment by LiorBanai** [comment]
@MelbourneDeveloper  no problem,
BTW microsoft  publish a post on this last week:
https://devblogs.microsoft.com/dotnet/improving-debug-time-productivity-with-source-link/

**Comment by MelbourneDeveloper** [comment]
@LiorBanai I'm guessing this will only work if I automatically build the NuGet package, but I've removed that from all the projects because I'm now doing this with NuGet pack in the pipelines. I need to understand how to do this with NuGet pack.

**Comment by MelbourneDeveloper** [comment]
@LiorBanai Hi. I compiled the Nuget package in release mode from your branch. The outputted Nuget package doesn't seem to be any different. This is the outputted nuspec:

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Device.Net</id>
    <version>4.0.0-alpha</version>
    <authors>Christian Findlay</authors>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <license type="file">LICENSE</license>
    <licenseUrl>https://aka.ms/deprecateLicenseUrl</licenseUrl>
    <projectUrl>https://github.com/MelbourneDeveloper/Device.Net</projectUrl>
    <description>Cross platform C# library for talking to connected devices in a uniform way through dependency injection.

			Alpha version. Please use 3.x for a stable release</description>
    <releaseNotes>Alpha version. Please use 3.x for a stable release</releaseNotes>
    <copyright>Copyright (c) 2020 Christian Findlay</copyright>
    <tags>Hid USB Android UWP Windows C# MacOS Linux</tags>
    <repository type="git" url="https://github.com/MelbourneDeveloper/Device.Net" commit="e56dacef234cf18f9a57fadaef1750ad69ff0024" />
    <dependencies>
      <group targetFramework=".NETFramework4.5" />
      <group targetFramework=".NETStandard2.0">
        <dependency id="Microsoft.Extensions.Logging.Abstractions" version="3.1.7" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

And, this is the .netstandard lib folder inside the nugget package:

image

Am I doing something wrong? How is this supposed to work?

**Comment by MelbourneDeveloper** [comment]
@LiorBanai actually, it outputted a file Device.Net.4.0.0-alpha.snupkg

So, it looks like there is a new Nuget format now...

**Comment by MelbourneDeveloper** [comment]
@LiorBanai it is outputting the package as a separate "symbols package". The doco is [here](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg)

That's pretty strange. Are they saying that we have to upload a Nuget package and separate symbols package? I looked at the structure and they are almost identical.

**Comment by LiorBanai** [comment]
@MelbourneDeveloper ,
Yeah the idea is that the symbols are now linked to the specific nuget at nuget .org so visual studio know how to read them.
e.g:
image

You can check if all is ok by opening the nuget in Nuget package Explorer: 
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer

e.g:
image

**Comment by LiorBanai** [comment]
Another option is to embedded the symbols inside the nuget itself but this is less recommended since the nuget file will be larger

**Comment by MelbourneDeveloper** [comment]
Awesome. Thanks @LiorBanai . This helps a lot because I need a way to validate that it worked.

**Comment by LiorBanai** [comment]
@MelbourneDeveloper in the next release I'll also check in code by trying to step into the nuget code from Visual studio :)

**Comment by LiorBanai** [comment]
BTW if there a connect/disconnect event when a usb device is connected removed?

**Comment by MelbourneDeveloper** [comment]
@LiorBanai the quick answer is that there is a class called DeviceListener for that but the documentation is a out of date and it's not really the recommended approach anymore. The new documentation will come soon. 

https://github.com/MelbourneDeveloper/Device.Net/wiki/Device-Listener

**Comment by LiorBanai** [comment]
@MelbourneDeveloper  Thanks!

**Comment by MelbourneDeveloper** [comment]
@LiorBanai 

Unfortunately, it's not working. I added the source link NuGet to all the projects and rebuilt everything. 

Then, ran this and got the result below:

`C:\Code\Device.Net>c:\temp\nuget pack Build/NuSpecs/Device.Net.nuspec -Symbols -SymbolPackageFormat snupkg`

> Attempting to build package from 'Device.Net.nuspec'.
> Successfully created package 'C:\Code\Device.Net\Device.Net.4.0.3-alpha.nupkg'.
> Successfully created package 'C:\Code\Device.Net\Device.Net.4.0.3-alpha.snupkg'.

It pumped out the .snupkg but there is no source link:
image

**Comment by LiorBanai** [comment]
That is actually looka good. Open the nuget file. Not the nuget symbol file.

**Comment by MelbourneDeveloper** [comment]
@LiorBanai cool. This is what I see. Is this what you expect?

image

**Comment by MelbourneDeveloper** [comment]
@LiorBanai do you recommend that I upload the .snupkg files to Nuget.org now?

**Comment by LiorBanai** [comment]
yeah looks good. The untrack file is option in the csproj that add auto genereated files  from the obj folder (some people disable it but I found it useful).
Upload both files and later I'll check it directly from visual studio

**Comment by MelbourneDeveloper** [comment]
@LiorBanai damn. It doesn't work.

image

https://www.nuget.org/packages/Device.Net/4.0.3-alpha

**Comment by LiorBanai** [comment]
I'll check what is wrong later today.

**Comment by LiorBanai** [comment]
@MelbourneDeveloper  Are you sure you uploaded the correct files? V 4.0.3 is 3 days ago.
You should first upload the nuget it self (V4.0.4?) and after that the symbol file for the same version...

**Comment by MelbourneDeveloper** [comment]
@LiorBanai I juust bumped the version a few minutes ago. Now I'm getting a different error but I think I've fixed it:

> The symbol package Hid.Net 4.0.4-alpha failed validation because of the following reason(s):
> •	The uploaded symbols package contains one or more pdbs that are not portable.
> Your symbol package was not published on NuGet Gallery and is not available for consumption.
> You can reupload your symbol package once you've fixed the issue with it.

**Comment by LiorBanai** [comment]
Oh right. You need to set in the project the pdb type to portable. I forgot the when making the changes..

**Comment by MelbourneDeveloper** [comment]
@LiorBanai all done:

https://github.com/MelbourneDeveloper/Device.Net/commit/adba12a13e73b916c29c143032aabf3c063f1b00

**Comment by MelbourneDeveloper** [comment]
@LiorBanai nope. No good. Same problem again:

https://www.nuget.org/packages/Device.Net/4.0.4-alpha

image

Source link sounds great in theory but any time Microsoft says just do x,y,z - it's easy! You know you are in for excruciating pain that destroys your time.

**Comment by MelbourneDeveloper** [comment]
@LiorBanai thanks for your contribution. Unfortunately, my project refactors shifted things around too much to directly merge your code, but you motivated me to get this done and pointed me in the right direction. Your help also motivated [this article](https://christianfindlay.com/2020/12/25/source-link-nuget-azure-pipelines/)

**Comment by MelbourneDeveloper** [comment]
The latest version of the NuGets now support Source Link (4.0.5-alpha and above)

**Comment by LiorBanai** [comment]
@MelbourneDeveloper, glad you figured out what was the issue :)

**Pull request closed without merging**
